In [62]:
 import pandas as pd

In [63]:
df = pd.DataFrame([11,22,33])
df

    0
0  11
1  22
2  33

In [64]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

Creating DataFrame

In [65]:
data = {
    'Name': ['NAINIKA', 'GANESH', 'HARRY', 'DAL-MI'],
    'Age': [20, 100, 24, 32],
    'Salary': [1000, 2000 , 3000 , 4000]
}

In [66]:
df = pd.DataFrame(data)
df

      Name  Age  Salary
0  NAINIKA   20    1000
1   GANESH  100    2000
2    HARRY   24    3000
3   DAL-MI   32    4000

DataFrame Attributes

In [67]:
df

      Name  Age  Salary
0  NAINIKA   20    1000
1   GANESH  100    2000
2    HARRY   24    3000
3   DAL-MI   32    4000

In [68]:
df.size

12

In [69]:
df.shape

(4, 3)

In [70]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [71]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [72]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace= True)

In [73]:
df.empty

False

Inspection of DataFrame

In [74]:
df

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

In [75]:
df.head(2)

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000

In [76]:
df.tail(2)

     Name  Age  Monthly_Salary
2   HARRY   24            3000
3  DAL-MI   32            4000

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [78]:
df.describe()

              Age  Monthly_Salary
count    4.000000        4.000000
mean    44.000000     2500.000000
std     37.665192     1290.994449
min     20.000000     1000.000000
25%     23.000000     1750.000000
50%     28.000000     2500.000000
75%     49.000000     3250.000000
max    100.000000     4000.000000

Saved and Load Data from csv

In [79]:
df.to_csv('Test_data.csv', index=False)
load_df = pd.read_csv('Test_data.csv')
load_df

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

Column Selection

In [80]:
df

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

In [81]:
df[['Name']]

      Name
0  NAINIKA
1   GANESH
2    HARRY
3   DAL-MI

In [82]:
df[['Name', 'Monthly_Salary']]

      Name  Monthly_Salary
0  NAINIKA            1000
1   GANESH            2000
2    HARRY            3000
3   DAL-MI            4000

Row Selection

In [83]:
df

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

In [84]:
df.loc[df.Name=='NAINIKA']

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000

In [85]:
df.loc[0:2]

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000

In [86]:
df.iloc[1]

Name              GANESH
Age                  100
Monthly_Salary      2000
Name: 1, dtype: object

In [87]:
df.iloc[0:2]

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000

Filter DataFrame

In [88]:
df

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

In [89]:
df[df['Age'] > 20]

     Name  Age  Monthly_Salary
1  GANESH  100            2000
2   HARRY   24            3000
3  DAL-MI   32            4000

In [90]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 3000)]

     Name  Age  Monthly_Salary
2   HARRY   24            3000
3  DAL-MI   32            4000

In [91]:
df.where(df['Age'] >= 18)

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

In [92]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

      Name  Age  Monthly_Salary
0  NAINIKA   20            1000
1   GANESH  100            2000
2    HARRY   24            3000
3   DAL-MI   32            4000

Add Column

In [93]:
df['Team'] = ['CEO', 'CTO', 'HR', 'DS']
df

      Name  Age  Monthly_Salary Team
0  NAINIKA   20            1000  CEO
1   GANESH  100            2000  CTO
2    HARRY   24            3000   HR
3   DAL-MI   32            4000   DS

In [94]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

      Name  Age  Monthly_Salary Team  Bonus
0  NAINIKA   20            1000  CEO  200.0
1   GANESH  100            2000  CTO  400.0
2    HARRY   24            3000   HR  600.0
3   DAL-MI   32            4000   DS  800.0

Add Row

In [95]:
df.loc[len(df)] = ['KRISHNA', 21, 2100, 'AIML', 200]
df

      Name  Age  Monthly_Salary  Team  Bonus
0  NAINIKA   20            1000   CEO  200.0
1   GANESH  100            2000   CTO  400.0
2    HARRY   24            3000    HR  600.0
3   DAL-MI   32            4000    DS  800.0
4  KRISHNA   21            2100  AIML  200.0

Delete Value

In [96]:
df.drop(df[df.Name == 'NAINIKA'].index)

      Name  Age  Monthly_Salary  Team  Bonus
1   GANESH  100            2000   CTO  400.0
2    HARRY   24            3000    HR  600.0
3   DAL-MI   32            4000    DS  800.0
4  KRISHNA   21            2100  AIML  200.0

In [97]:
df.drop('Bonus', axis=1)

      Name  Age  Monthly_Salary  Team
0  NAINIKA   20            1000   CEO
1   GANESH  100            2000   CTO
2    HARRY   24            3000    HR
3   DAL-MI   32            4000    DS
4  KRISHNA   21            2100  AIML

Sort Value

In [98]:
df.sort_values('Monthly_Salary')

      Name  Age  Monthly_Salary  Team  Bonus
0  NAINIKA   20            1000   CEO  200.0
1   GANESH  100            2000   CTO  400.0
4  KRISHNA   21            2100  AIML  200.0
2    HARRY   24            3000    HR  600.0
3   DAL-MI   32            4000    DS  800.0

Working with Data Value

In [99]:
df

      Name  Age  Monthly_Salary  Team  Bonus
0  NAINIKA   20            1000   CEO  200.0
1   GANESH  100            2000   CTO  400.0
2    HARRY   24            3000    HR  600.0
3   DAL-MI   32            4000    DS  800.0
4  KRISHNA   21            2100  AIML  200.0

In [100]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03', '2024-04-07']
df

      Name  Age  Monthly_Salary  Team  Bonus         DOJ
0  NAINIKA   20            1000   CEO  200.0  2024-01-01
1   GANESH  100            2000   CTO  400.0  2024-01-15
2    HARRY   24            3000    HR  600.0  2024-03-28
3   DAL-MI   32            4000    DS  800.0  2024-03-03
4  KRISHNA   21            2100  AIML  200.0  2024-04-07

In [101]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [102]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [103]:
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
4      Sunday
Name: DOJ, dtype: object

In [104]:
df['Month'] = df['DOJ'].dt.month
df

      Name  Age  Monthly_Salary  Team  Bonus        DOJ  Month
0  NAINIKA   20            1000   CEO  200.0 2024-01-01      1
1   GANESH  100            2000   CTO  400.0 2024-01-15      1
2    HARRY   24            3000    HR  600.0 2024-03-28      3
3   DAL-MI   32            4000    DS  800.0 2024-03-03      3
4  KRISHNA   21            2100  AIML  200.0 2024-04-07      4

In [105]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
4   2024-07-06
Name: DOJ, dtype: datetime64[ns]

Handling with Null Values

In [106]:
df

      Name  Age  Monthly_Salary  Team  Bonus        DOJ  Month
0  NAINIKA   20            1000   CEO  200.0 2024-01-01      1
1   GANESH  100            2000   CTO  400.0 2024-01-15      1
2    HARRY   24            3000    HR  600.0 2024-03-28      3
3   DAL-MI   32            4000    DS  800.0 2024-03-03      3
4  KRISHNA   21            2100  AIML  200.0 2024-04-07      4

In [107]:
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus    DOJ  Month
0  False  False           False  False  False  False  False
1  False  False           False  False  False  False  False
2  False  False           False  False  False  False  False
3  False  False           False  False  False  False  False
4  False  False           False  False  False  False  False

In [108]:
import numpy as np

In [109]:
df.loc[df.Name=='NAINIKA', 'Monthly_Salary'] = np.nan
df

      Name  Age  Monthly_Salary  Team  Bonus        DOJ  Month
0  NAINIKA   20             NaN   CEO  200.0 2024-01-01      1
1   GANESH  100          2000.0   CTO  400.0 2024-01-15      1
2    HARRY   24          3000.0    HR  600.0 2024-03-28      3
3   DAL-MI   32          4000.0    DS  800.0 2024-03-03      3
4  KRISHNA   21          2100.0  AIML  200.0 2024-04-07      4

In [110]:
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus    DOJ  Month
0  False  False            True  False  False  False  False
1  False  False           False  False  False  False  False
2  False  False           False  False  False  False  False
3  False  False           False  False  False  False  False
4  False  False           False  False  False  False  False

In [111]:
df.isnull().sum()

Name              0
Age               0
Monthly_Salary    1
Team              0
Bonus             0
DOJ               0
Month             0
dtype: int64

In [112]:
df.fillna(0)

      Name  Age  Monthly_Salary  Team  Bonus        DOJ  Month
0  NAINIKA   20             0.0   CEO  200.0 2024-01-01      1
1   GANESH  100          2000.0   CTO  400.0 2024-01-15      1
2    HARRY   24          3000.0    HR  600.0 2024-03-28      3
3   DAL-MI   32          4000.0    DS  800.0 2024-03-03      3
4  KRISHNA   21          2100.0  AIML  200.0 2024-04-07      4

Aggregation

In [113]:
df['Month'].value_counts()

Month
1    2
3    2
4    1
Name: count, dtype: int64

In [114]:
df[df['Month']==1].value_counts()

Name    Age  Monthly_Salary  Team  Bonus  DOJ         Month
GANESH  100  2000.0          CTO   400.0  2024-01-15  1        1
Name: count, dtype: int64

Group by

In [115]:
df.groupby('Month')['Monthly_Salary'].sum()

Month
1    2000.0
3    7000.0
4    2100.0
Name: Monthly_Salary, dtype: float64

In [116]:
df.groupby('Month').agg({'Monthly_Salary': 'mean', 'Name': 'count'})

       Monthly_Salary  Name
Month
1              2000.0     2
3              3500.0     2
4              2100.0     1

Concatenate Dataframe

In [117]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [118]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [119]:
pd.concat([df1, df2], axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [120]:
pd.concat([df1, df2], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

Merge DataFrame

In [121]:
pd.merge(df1, df2, how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [122]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77